[package]
name = "taskify_web"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
dotenv = "0.15.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.1", features = ["full"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing = "0.1"
diesel_migrations = "2"
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
r2d2 = "0.8"
leptess = "0.14"
reqwest = { version = "0.11", features = ["json", "multipart"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tower-http = { version = "0.6.8", features = ["fs"] }
