[package]
name = "taskify_desktop"
version.workspace = true
edition.workspace = true

[dependencies]
eframe = { version = "0.34.1", default-features = false, features = [
    "default",
] }
egui = { version = "0.34.1", features = ["default"] }
taskify_core = { version = "*", path = "../taskify_core", default-features = false }
dotenv = "0.15.0"
